media:
  input: public
  output: /public

content:
  - name: posts
    label: Posts
    type: collection
    path: content
    format: yaml-frontmatter
    filename: "{primary}.md"
    fields:
      - name: title
        type: string
        required: true
      - name: date
        type: date
        required: true
      - name: category
        type: string
      - name: excerpt
        type: text
        required: true
        options:
          maxlength: 200
      - name: tags
        type: string
        list: true
      - name: meta_title
        type: string
        description: "Custom title for SEO (optional)"
      - name: body
        type: rich-text
    view:
      primary: title
      sort: date
      order: desc
      fields:
        - title
        - date
        - category
        - tags
